'use client';
import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';

type Promo = { id: string; code: string; value_ngn: number; expires_at?: string | null; usage_limit?: number | null; per_user_limit: number; is_active: boolean };
const EMPTY = { code: '', value_ngn: '500', expires_at: '', usage_limit: '', per_user_limit: '1', is_active: true };

export default function AdminPromoCodesPage(){
  const [rows,setRows]=useState<Promo[]>([]); const [form,setForm]=useState(EMPTY); const [msg,setMsg]=useState(''); const [refBonus,setRefBonus]=useState('500');
  async function load(){ const [res,settings]=await Promise.all([fetch('/api/admin/promo-codes',{cache:'no-store'}), fetch('/api/admin/settings',{cache:'no-store'})]); if(res.ok) setRows(await res.json()); if(settings.ok){ const data=await settings.json(); setRefBonus(data.referral_bonus_ngn || '500'); } }
  useEffect(()=>{load();},[]);
  async function create(e:React.FormEvent){ e.preventDefault(); setMsg(''); const res=await fetch('/api/admin/promo-codes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const data=await res.json(); if(!res.ok) setMsg(data.error||'Save failed'); else { setForm(EMPTY); load(); } }
  async function remove(id:string){ await fetch(`/api/admin/promo-codes/${id}`,{method:'DELETE'}); load(); }
  async function saveReferralBonus(){ await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({referral_bonus_ngn:refBonus})}); setMsg('Referral bonus saved.'); }
  return <div className="p-8"><h1 className="text-xl font-bold uppercase tracking-widest text-fn-text">Promo Codes</h1><p className="mt-1 text-xs text-fn-muted">Create wallet-credit promo codes and manage usage limits.</p><section className="mt-6 rounded border border-fn-gborder bg-fn-card p-4"><p className="fn-label mb-2">Referral Bonus</p><div className="flex gap-2"><input type="number" value={refBonus} onChange={(e)=>setRefBonus(e.target.value)} className="border border-fn-gborder bg-fn-black px-3 py-2 text-xs outline-none"/><button type="button" onClick={saveReferralBonus} className="fn-btn px-3">Save ₦ Bonus</button></div></section><form onSubmit={create} className="mt-6 grid gap-3 rounded border border-fn-gborder bg-fn-card p-4 md:grid-cols-6"><input value={form.code} onChange={(e)=>setForm({...form,code:e.target.value})} placeholder="CODE" className="border border-fn-gborder bg-fn-black px-3 py-2 text-xs uppercase outline-none" required/><input type="number" value={form.value_ngn} onChange={(e)=>setForm({...form,value_ngn:e.target.value})} placeholder="Value" className="border border-fn-gborder bg-fn-black px-3 py-2 text-xs outline-none" required/><input type="datetime-local" value={form.expires_at} onChange={(e)=>setForm({...form,expires_at:e.target.value})} className="border border-fn-gborder bg-fn-black px-3 py-2 text-xs outline-none"/><input type="number" value={form.usage_limit} onChange={(e)=>setForm({...form,usage_limit:e.target.value})} placeholder="Usage limit" className="border border-fn-gborder bg-fn-black px-3 py-2 text-xs outline-none"/><input type="number" value={form.per_user_limit} onChange={(e)=>setForm({...form,per_user_limit:e.target.value})} placeholder="Per user" className="border border-fn-gborder bg-fn-black px-3 py-2 text-xs outline-none"/><button className="fn-btn inline-flex items-center justify-center gap-2"><Plus size={14}/> Add</button></form>{msg&&<p className="mt-3 text-xs text-fn-red">{msg}</p>}<div className="mt-6 space-y-2">{rows.map(row=><div key={row.id} className="flex items-center justify-between border border-fn-gborder bg-fn-card px-3 py-2 text-xs"><span><b className="text-fn-green">{row.code}</b> · ₦{Number(row.value_ngn).toLocaleString()} · {row.is_active?'Active':'Inactive'}</span><button onClick={()=>remove(row.id)} className="text-fn-red"><Trash2 size={14}/></button></div>)}</div></div>;
}
