'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Shield, Trophy } from 'lucide-react';
import { useGame } from '@/context/GameContext';

type Athlete = { id:string; name:string; ign:string; known_name?:string|null; team:string|null; role:string|null; status:string; photo_url:string|null; overall_rating:number; rating:number; kills:number; assists:number; damage:number; winrate:number; previous_aliases?: string[] | string | null; previous_teams?: {team:string;years:string}[] | string | null; achievements?: {title:string;date:string}[] | string | null; bio:string|null };
function parseArray(v: unknown){ if(!v) return []; if(Array.isArray(v)) return v; try{return JSON.parse(String(v))}catch{return String(v).split(',').map((s:string)=>s.trim()).filter(Boolean)} }
function parseObjects(v: unknown){ const a=parseArray(v); return Array.isArray(a)?a.filter((x)=>x&&typeof x==='object'):[] }
export default function AthleteDetail({ params }: { params: { id: string } }) {
  const { selectedGame } = useGame(); const primary=selectedGame.colors.primary;
  const [a,setA]=useState<Athlete|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch(`/api/athletes/${params.id}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setA).finally(()=>setLoading(false))},[params.id]);
  if(loading) return <div className="min-h-screen p-8 text-fn-muted">Loading athlete…</div>;
  if(!a) return <div className="min-h-screen p-8"><p className="text-fn-muted">Athlete not found.</p><Link href="/athletes" className="text-fn-green">Back to roster</Link></div>;
  const aliases=parseArray(a.previous_aliases); const teams=parseObjects(a.previous_teams); const achievements=parseObjects(a.achievements); const rating=Number(a.overall_rating ?? a.rating ?? 0);
  return <div className="min-h-screen p-4 sm:p-8 lg:p-12"><Link href="/athletes" className="fn-label">← ALL ATHLETES</Link><section className="mt-4 rounded-sm border border-fn-gborder bg-fn-card p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-24 w-24 items-center justify-center overflow-hidden rounded-sm border" style={{borderColor:primary,background:`${primary}15`}}>{a.photo_url?<img src={a.photo_url} alt={a.ign} className="h-full w-full object-cover"/>:<Shield style={{color:primary}}/>}</div><div className="flex-1"><p className="fn-label">{a.status} · {a.role || 'Player'}</p><h1 className="font-display text-4xl font-black uppercase text-fn-text">{a.known_name || a.ign}</h1><p className="text-xs text-fn-muted">{a.name}{aliases.length>0?` · Alias: ${aliases.join(' · ')}`:''}</p></div><div className="text-center"><div className="font-display text-5xl font-black" style={{color:primary}}>{rating}</div><div className="fn-label">RTG</div></div></div>{a.bio&&<p className="mt-5 text-sm leading-relaxed text-fn-muted">{a.bio}</p>}</section><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['KLS',a.kills],['AST',a.assists],['DMG',a.damage],['WR',`${a.winrate}%`]].map(([l,v])=><div key={l} className="rounded-sm border border-fn-gborder bg-fn-card p-4 text-center"><div className="font-display text-2xl font-black text-fn-text">{v}</div><div className="fn-label">{l}</div></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-3"><article className="rounded-sm border border-fn-gborder bg-fn-card p-4"><h2 className="fn-label mb-3" style={{color:primary}}>TEAMS</h2><p className="text-xs font-bold text-fn-text">Current: {a.team || 'Free Agent'}</p>{teams.map((t: { team?: string; years?: string },i:number)=><p key={i} className="mt-2 text-xs text-fn-muted">Previous: {t.team} {t.years}</p>)}</article><article className="rounded-sm border border-fn-gborder bg-fn-card p-4 lg:col-span-2"><h2 className="fn-label mb-3 flex items-center gap-2"><Trophy size={12} style={{color:primary}}/> ACHIEVEMENTS / TITLES</h2>{achievements.length?achievements.map((x: { title?: string; date?: string },i:number)=><p key={i} className="mb-2 text-xs text-fn-text">{x.title} <span className="text-fn-muted">{x.date}</span></p>):<p className="text-xs text-fn-muted">No titles recorded yet.</p>}</article></div></div>;
}
