'use client';

import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import AdminModal from '@/components/admin/AdminModal';
import AdminTable from '@/components/admin/AdminTable';
import { Field, Input, Select, SubmitBtn } from '@/components/admin/Field';
import OptimizedImage from '@/components/common/OptimizedImage';

type Partner = Record<string, unknown> & { id: string; name: string; logo_url: string; website_url?: string; sort_order: number; status: string };
const EMPTY = { name: '', logo_url: '', website_url: '', sort_order: '0', status: 'Published' };

export default function AdminPartnersPage() {
  const [rows, setRows] = useState<Partner[]>([]); const [form, setForm] = useState({ ...EMPTY }); const [editing, setEditing] = useState<Partner | null>(null); const [logoFile, setLogoFile] = useState<File | null>(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); const response = await fetch('/api/partners?admin=1', { cache: 'no-store' }); setRows(response.ok ? await response.json() : []); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const field = (key: keyof typeof EMPTY) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const add = () => { setEditing(null); setLogoFile(null); setForm({ ...EMPTY, sort_order: String(rows.length) }); setError(''); setOpen(true); };
  const edit = (row: Partner) => { setEditing(row); setLogoFile(null); setForm({ name: row.name, logo_url: row.logo_url, website_url: String(row.website_url || ''), sort_order: String(row.sort_order || 0), status: row.status }); setError(''); setOpen(true); };
  const upload = async () => { if (!logoFile) return null; const body = new FormData(); body.append('file', logoFile); body.append('bucket', 'partners'); const response = await fetch('/api/upload', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Logo upload failed.'); return data.url as string; };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const logo_url = await upload() || form.logo_url; const response = await fetch('/api/partners', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, logo_url, id: editing?.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Partner save failed.'); setOpen(false); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Partner save failed.'); } finally { setSaving(false); } };
  const remove = async (row: Partner) => { if (!confirm(`Delete ${row.name}?`)) return; const response = await fetch(`/api/partners?id=${encodeURIComponent(row.id)}`, { method: 'DELETE' }); if (!response.ok) { const data = await response.json(); setError(data.error || 'Partner delete failed.'); return; } await load(); };
  return <div className="p-8"><div className="mb-4 flex items-center justify-between"><div><h1 className="text-xl font-bold uppercase tracking-widest text-fn-text">Partners</h1><p className="text-xs text-fn-muted">Manage homepage sponsor logos and their display order.</p></div><button onClick={add} className="flex items-center gap-2 rounded bg-fn-green px-4 py-2 text-sm font-bold uppercase tracking-widest text-fn-black"><Plus size={14} /> Add Partner</button></div>{error && <p className="mb-3 rounded border border-fn-red/20 bg-fn-red/10 px-3 py-2 text-xs text-fn-red">{error}</p>}<AdminTable loading={loading} rows={rows} onEdit={edit} onDelete={remove} emptyText="No partners yet" columns={[{ key: 'logo_url', label: 'Logo', render: (row) => <OptimizedImage src={String(row.logo_url)} alt="" className="h-8 w-16 object-contain" /> }, { key: 'name', label: 'Name' }, { key: 'sort_order', label: 'Order' }, { key: 'status', label: 'Status' }]} /><AdminModal title={editing ? 'Edit Partner' : 'Add Partner'} open={open} onClose={() => setOpen(false)}><form onSubmit={submit} className="space-y-3"><Field label="Name" required><Input value={form.name} onChange={field('name')} required /></Field><Field label="Logo Upload"><Input type="file" accept="image/*" onChange={(event) => setLogoFile(event.target.files?.[0] || null)} /><p className="mt-1 text-[10px] text-fn-muted">Uploaded file takes priority over a pasted URL.</p></Field><Field label="Logo URL" required><Input value={form.logo_url} onChange={field('logo_url')} required={!logoFile} placeholder="https://..." /></Field><Field label="Website URL"><Input value={form.website_url} onChange={field('website_url')} placeholder="https://..." /></Field><div className="grid grid-cols-2 gap-3"><Field label="Sort Order"><Input type="number" value={form.sort_order} onChange={field('sort_order')} /></Field><Field label="Status"><Select value={form.status} onChange={field('status')}><option>Published</option><option>Draft</option></Select></Field></div><SubmitBtn loading={saving} label={editing ? 'Update Partner' : 'Add Partner'} /></form></AdminModal></div>;
}
