'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Save } from 'lucide-react';

type Row = { id: string; athleteId: string; athleteName: string; participated: boolean; kills: string; topThree: boolean; matchWin: boolean; mvp: boolean; goals: string; result: 'win' | 'loss' | 'draw'; conceded: string; points?: number };
type Athlete = { id: string; name?: string; ign?: string; known_name?: string | null };
type Config = Record<string, number>;
type SavedStat = { athlete_id: string; participated?: boolean; kills?: number; top_three_finish?: boolean; match_win?: boolean; mvp?: boolean; goals?: number; result?: 'win' | 'loss' | 'draw'; goals_conceded?: number; fantasy_points?: number };
const label = (athlete: Athlete) => athlete.known_name || athlete.ign || athlete.name || 'Unknown athlete';

export default function AdminFantasyMatchStatsPage({ params }: { params: { gameweekId: string; matchId: string } }) {
  const [rows, setRows] = useState<Row[]>([]); const [gameSlug, setGameSlug] = useState('pubg-mobile'); const [config, setConfig] = useState<Config>({}); const [error, setError] = useState(''); const football = gameSlug === 'fc-mobile';
  useEffect(() => { fetch(`/api/admin/fantasy/matches/${params.matchId}/stats`, { cache: 'no-store' }).then(async r => r.ok ? r.json() : Promise.reject(new Error((await r.json()).error))).then(data => { setGameSlug(data.match.game_slug); setConfig(data.config || {}); const stats = new Map<string, SavedStat>((data.stats || []).map((stat: SavedStat) => [stat.athlete_id, stat])); setRows((data.athletes || []).map((a: Athlete) => { const s = stats.get(a.id) || {}; return { id: a.id, athleteId: a.id, athleteName: label(a), participated: s.participated ?? true, kills: String(s.kills ?? 0), topThree: Boolean(s.top_three_finish), matchWin: Boolean(s.match_win), mvp: Boolean(s.mvp), goals: String(s.goals ?? 0), result: s.result || 'draw', conceded: String(s.goals_conceded ?? 0), points: s.fantasy_points }; })); }).catch(e => setError(e.message)); }, [params.matchId]);
  const calc = (row: Row) => football ? (row.participated ? Number(config.appearance_points ?? 1) : 0) + Number(row.goals || 0) * Number(config.goal_points ?? 5) + (row.result === 'win' ? Number(config.win_points ?? 3) : row.result === 'loss' ? Number(config.loss_points ?? -2) : 0) + Number(row.conceded || 0) * Number(config.conceded_points ?? -1) : (row.participated ? Number(config.participation_points ?? 1) : 0) + Number(row.kills || 0) * Number(config.kill_points ?? 2) + (row.matchWin ? Number(config.match_win_points ?? 10) : row.topThree ? Number(config.top_three_finish_points ?? 5) : 0) + (row.mvp ? Number(config.mvp_bonus ?? 5) : 0);
  const invalid = useMemo(() => rows.some(r => [r.kills, r.goals, r.conceded].some(v => !Number.isFinite(Number(v)) || Number(v) < 0)), [rows]);
  const patch = (id: string, changes: Partial<Row>) => setRows(current => current.map(row => row.id === id ? { ...row, ...changes } : row));
  async function save(finalize = false) { if (invalid) { setError('Goals, goals conceded, and kills must be non-negative numbers.'); return; } const calculated = rows.map(row => ({ ...row, points: calc(row) })); setRows(calculated); const response = await fetch(`/api/admin/fantasy/matches/${params.matchId}/stats`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ finalize, rows: calculated.map(r => ({ athlete_id: r.athleteId, participated: r.participated, kills: Number(r.kills), top_three_finish: r.topThree, match_win: r.matchWin, mvp: r.mvp, goals: Number(r.goals), result: r.result, goals_conceded: Number(r.conceded) })) }) }); if (!response.ok) setError((await response.json()).error || 'Unable to save stats.'); else setError(''); }
  return <div className="p-8"><div className="mb-5 text-xs uppercase tracking-widest text-fn-muted"><Link className="text-fn-green" href="/admin/fantasy">Fantasy League</Link> / Stat Entry</div><h1 className="font-display text-2xl font-black uppercase">{football ? 'FC Mobile football stat entry' : 'PUBG Mobile match stat entry'}</h1><p className="mt-2 text-sm text-fn-muted">{football ? 'Draws receive 0 result points. Conceded is applied once per goal conceded while the athlete was on the pitch.' : 'Stats are calculated with the PUBG Mobile configuration.'}</p>{error && <p className="mt-3 flex gap-2 text-xs text-fn-red"><AlertTriangle size={14} />{error}</p>}<div className="mt-5 overflow-x-auto border border-fn-gborder"><table className="w-full min-w-[800px] text-xs"><thead><tr className="bg-fn-dark text-left"><th className="p-3">Athlete</th><th>Appeared</th>{football ? <><th>Goals</th><th>Result</th><th>Goals conceded</th></> : <><th>Kills</th><th>Top 3</th><th>Win</th><th>MVP</th></>}<th>Calculated</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-t border-fn-gborder"><td className="p-3 font-black">{row.athleteName}</td><td><input type="checkbox" checked={row.participated} onChange={e => patch(row.id, { participated: e.target.checked })} /></td>{football ? <><td><input type="number" min="0" value={row.goals} onChange={e => patch(row.id, { goals: e.target.value })} /></td><td><select value={row.result} onChange={e => patch(row.id, { result: e.target.value as Row['result'] })}><option value="win">Win</option><option value="loss">Loss</option><option value="draw">Draw</option></select></td><td><input type="number" min="0" value={row.conceded} onChange={e => patch(row.id, { conceded: e.target.value })} /></td></> : <><td><input type="number" min="0" value={row.kills} onChange={e => patch(row.id, { kills: e.target.value })} /></td><td><input type="checkbox" checked={row.topThree} onChange={e => patch(row.id, { topThree: e.target.checked })} /></td><td><input type="checkbox" checked={row.matchWin} onChange={e => patch(row.id, { matchWin: e.target.checked })} /></td><td><input type="checkbox" checked={row.mvp} onChange={e => patch(row.id, { mvp: e.target.checked })} /></td></>}<td className="font-black text-fn-green">{row.points ?? calc(row)}</td></tr>)}</tbody></table></div><div className="mt-4 flex gap-3"><button onClick={() => save(false)} className="bg-fn-green px-4 py-3 text-xs font-black text-fn-black"><Save size={14} className="mr-2 inline" />Save & Calculate Points</button><button onClick={() => save(true)} className="border border-fn-green px-4 py-3 text-xs font-black text-fn-green">Finalize</button></div></div>;
}
