-- Fantasy League extends the existing athletes roster instead of creating a duplicate player database.
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS fantasy_price NUMERIC(12,2) DEFAULT 750000;
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS recent_fantasy_points NUMERIC(8,2) DEFAULT 0;
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS total_fantasy_points NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS fantasy_status TEXT DEFAULT 'available' CHECK (fantasy_status IN ('available','injured','suspended','inactive'));
CREATE TABLE IF NOT EXISTS public.fantasy_scoring_config (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL DEFAULT 'default', participation_points NUMERIC(6,2) DEFAULT 1, kill_points NUMERIC(6,2) DEFAULT 2, top_three_finish_points NUMERIC(6,2) DEFAULT 5, match_win_points NUMERIC(6,2) DEFAULT 10, mvp_bonus NUMERIC(6,2) DEFAULT 5, captain_multiplier NUMERIC(4,2) DEFAULT 2, triple_captain_multiplier NUMERIC(4,2) DEFAULT 3, finish_points_stack BOOLEAN DEFAULT false, chip_usage_limits JSONB DEFAULT '{"manual_substitute":{"per_gameweek":1},"triple_captain":{"per_season":1}}'::jsonb, substitution_rules JSONB DEFAULT '{"auto_sub_when_no_participation":true,"bench_priority":"user_order"}'::jsonb, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.fantasy_gameweeks (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, starts_at TIMESTAMPTZ, deadline_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ, status TEXT DEFAULT 'selection' CHECK (status IN ('selection','locked','scoring','complete')), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.fantasy_match_stats (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), gameweek_id UUID REFERENCES public.fantasy_gameweeks(id) ON DELETE CASCADE, athlete_id UUID REFERENCES public.athletes(id) ON DELETE CASCADE, kills INT DEFAULT 0, placement INT, match_win BOOLEAN DEFAULT false, top_three_finish BOOLEAN DEFAULT false, mvp BOOLEAN DEFAULT false, participated BOOLEAN DEFAULT true, fantasy_points NUMERIC(8,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(gameweek_id, athlete_id));
CREATE TABLE IF NOT EXISTS public.fantasy_squads (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL, gameweek_id UUID REFERENCES public.fantasy_gameweeks(id) ON DELETE SET NULL, starter_ids UUID[] DEFAULT '{}', bench_ids UUID[] DEFAULT '{}', captain_id UUID REFERENCES public.athletes(id) ON DELETE SET NULL, squad_value NUMERIC(12,2) DEFAULT 0, remaining_budget NUMERIC(12,2) DEFAULT 10000000, active_chip TEXT CHECK (active_chip IN ('triple_captain')), chip_usage JSONB DEFAULT '{}'::jsonb, total_points NUMERIC(10,2) DEFAULT 0, gameweek_points NUMERIC(10,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.fantasy_leagues (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, league_type TEXT DEFAULT 'private' CHECK (league_type IN ('global','private','friends','clan','community')), invite_code TEXT UNIQUE, owner_user_id UUID, created_at TIMESTAMPTZ DEFAULT NOW());
