-- Fantasy League extends the existing athletes roster instead of creating a duplicate player database.
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS fantasy_price NUMERIC(12,2) DEFAULT 750000;
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS recent_fantasy_points NUMERIC(8,2) DEFAULT 0;
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS total_fantasy_points NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.athletes ADD COLUMN IF NOT EXISTS fantasy_status TEXT DEFAULT 'available' CHECK (fantasy_status IN ('available','injured','suspended','inactive'));
CREATE TABLE IF NOT EXISTS public.fantasy_scoring_config (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL DEFAULT 'default', kill_points NUMERIC(6,2) DEFAULT 2, assist_points NUMERIC(6,2) DEFAULT 1, placement_points JSONB DEFAULT '{"1":15,"2":12,"3":10,"4":8,"5":6,"6":5,"7":4,"8":3,"9":2,"10":1}'::jsonb, chicken_dinner_bonus NUMERIC(6,2) DEFAULT 5, five_kill_bonus NUMERIC(6,2) DEFAULT 3, ten_kill_bonus NUMERIC(6,2) DEFAULT 6, mvp_bonus NUMERIC(6,2) DEFAULT 5, zero_kill_penalty NUMERIC(6,2) DEFAULT -2, early_elimination_penalty NUMERIC(6,2) DEFAULT -3, substitution_rules JSONB DEFAULT '{"auto_sub_when_no_participation":true,"bench_priority":"user_order"}'::jsonb, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.fantasy_gameweeks (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, starts_at TIMESTAMPTZ, deadline_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ, status TEXT DEFAULT 'selection' CHECK (status IN ('selection','locked','scoring','complete')), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.fantasy_match_stats (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), gameweek_id UUID REFERENCES public.fantasy_gameweeks(id) ON DELETE CASCADE, athlete_id UUID REFERENCES public.athletes(id) ON DELETE CASCADE, kills INT DEFAULT 0, assists INT DEFAULT 0, placement INT, chicken_dinner BOOLEAN DEFAULT false, mvp BOOLEAN DEFAULT false, participated BOOLEAN DEFAULT true, early_elimination BOOLEAN DEFAULT false, fantasy_points NUMERIC(8,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(gameweek_id, athlete_id));
CREATE TABLE IF NOT EXISTS public.fantasy_squads (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL, gameweek_id UUID REFERENCES public.fantasy_gameweeks(id) ON DELETE SET NULL, starter_ids UUID[] DEFAULT '{}', bench_ids UUID[] DEFAULT '{}', captain_id UUID REFERENCES public.athletes(id) ON DELETE SET NULL, squad_value NUMERIC(12,2) DEFAULT 0, remaining_budget NUMERIC(12,2) DEFAULT 10000000, total_points NUMERIC(10,2) DEFAULT 0, gameweek_points NUMERIC(10,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.fantasy_leagues (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, league_type TEXT DEFAULT 'private' CHECK (league_type IN ('global','private','friends','clan','community')), invite_code TEXT UNIQUE, owner_user_id UUID, created_at TIMESTAMPTZ DEFAULT NOW());
