'use client';
import { useEffect, useState } from 'react';
import { Bot, Gift, LogOut, Moon, Save, SearchCheck, Sun, User } from 'lucide-react';
import { useTheme } from '@/components/ThemeProvider';
import FontSettingsPanel from '@/components/common/FontSettingsPanel';

type Profile = { username?: string | null; first_name?: string | null; middle_name?: string | null; last_name?: string | null; date_of_birth?: string | null; referral_code?: string | null };
type Preferences = { show_notification_shortcuts?: boolean; match_alerts_enabled?: boolean };
type Referral = { id: string; referred_display: string; status: string; bonus_amount_ngn: number };
type VerifiedSelection = { wager_id: string; selection: string; live_odds: number; available: boolean; market?: { match_name?: string; question?: string } };
type VerifyResult = { slip_code?: string; verification_id?: string; status?: string; stake?: number; redeemable?: boolean; selections?: VerifiedSelection[] };

export default function SettingsPage() {
  const { theme, toggle } = useTheme();
  const [profile, setProfile] = useState<Profile>({});
  const [prefs, setPrefs] = useState<Preferences>({ show_notification_shortcuts: true, match_alerts_enabled: true });
  const [offers, setOffers] = useState<{ referral_code?: string; referrals?: Referral[] }>({});
  const [promo, setPromo] = useState('');
  const [message, setMessage] = useState('');
  const [verifyCode, setVerifyCode] = useState('');
  const [verifyResult, setVerifyResult] = useState<VerifyResult | null>(null);

  useEffect(() => { Promise.all([
    fetch('/api/settings/profile').then(r => r.ok ? r.json() : {}),
    fetch('/api/settings/preferences').then(r => r.ok ? r.json() : {}),
    fetch('/api/offers').then(r => r.ok ? r.json() : {}),
  ]).then(([profileData, prefData, offerData]) => { setProfile(profileData); setPrefs(prefData); setOffers(offerData); }); }, []);

  async function saveProfile() { setMessage(''); const res = await fetch('/api/settings/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(profile) }); const data = await res.json(); setMessage(res.ok ? 'Profile saved.' : data.error || 'Unable to save profile.'); }
  async function savePrefs(next: Preferences) { setPrefs(next); await fetch('/api/settings/preferences', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); }
  async function verifyBet() { setMessage(''); setVerifyResult(null); const res = await fetch(`/api/wager/slip?code=${encodeURIComponent(verifyCode)}`); const data = await res.json(); if (res.ok) setVerifyResult(data); else setMessage(data.error || 'Unable to verify bet slip.'); }
  async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); window.location.href = '/'; }
  async function redeem() { setMessage(''); const res = await fetch('/api/offers/redeem', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: promo }) }); const data = await res.json(); setMessage(res.ok ? 'Promo redeemed and wallet credited.' : data.error || 'Promo failed.'); }
  const referralUrl = typeof window === 'undefined' ? '' : `${window.location.origin}/register?ref=${offers.referral_code || profile.referral_code || ''}`;

  return <main className="min-h-screen bg-fn-black px-4 py-8 text-fn-text"><div className="mx-auto max-w-3xl space-y-5">
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label text-fn-green">Settings</p><h1 className="font-display text-3xl font-black uppercase tracking-widest">Account Command Center</h1></section>
    {message && <p className="border border-fn-green/30 bg-fn-green/10 px-3 py-2 text-xs text-fn-green">{message}</p>}
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label mb-3">Appearance</p><button type="button" onClick={toggle} className="inline-flex items-center gap-2 border border-fn-gborder px-3 py-2 text-xs font-black uppercase tracking-widest text-fn-muted hover:text-fn-green">{theme === 'dark' ? <Sun size={14}/> : <Moon size={14}/>} Switch to {theme === 'dark' ? 'Light' : 'Dark'} Mode</button><div className="mt-4"><p className="fn-label mb-2">Font Settings</p><FontSettingsPanel /></div></section>
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label mb-3">Notifications</p><label className="flex items-center justify-between gap-4 py-2 text-xs uppercase tracking-widest text-fn-muted"><span>Show notification shortcuts</span><input type="checkbox" checked={prefs.show_notification_shortcuts !== false} onChange={(e) => savePrefs({ ...prefs, show_notification_shortcuts: e.target.checked })} className="accent-fn-green" /></label><label className="flex items-center justify-between gap-4 py-2 text-xs uppercase tracking-widest text-fn-muted"><span>Match alerts</span><input type="checkbox" checked={prefs.match_alerts_enabled !== false} onChange={(e) => savePrefs({ ...prefs, match_alerts_enabled: e.target.checked })} className="accent-fn-green" /></label></section>
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label mb-3">Support</p><button type="button" onClick={() => window.dispatchEvent(new Event('fn-open-support-chat'))} className="fn-btn inline-flex items-center gap-2"><Bot size={14}/> Customer Support</button></section>
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label mb-3 flex items-center gap-2"><User size={12}/> My Profile</p><div className="grid gap-3 sm:grid-cols-2"><input value={profile.username || ''} onChange={(e) => setProfile({ ...profile, username: e.target.value })} placeholder="Username" className="border border-fn-gborder bg-fn-black px-3 py-2 text-sm outline-none"/><input type="date" value={profile.date_of_birth || ''} onChange={(e) => setProfile({ ...profile, date_of_birth: e.target.value })} className="border border-fn-gborder bg-fn-black px-3 py-2 text-sm outline-none"/><input value={profile.first_name || ''} onChange={(e) => setProfile({ ...profile, first_name: e.target.value })} placeholder="First Name" className="border border-fn-gborder bg-fn-black px-3 py-2 text-sm outline-none"/><input value={profile.middle_name || ''} onChange={(e) => setProfile({ ...profile, middle_name: e.target.value })} placeholder="Middle Name (optional)" className="border border-fn-gborder bg-fn-black px-3 py-2 text-sm outline-none"/><input value={profile.last_name || ''} onChange={(e) => setProfile({ ...profile, last_name: e.target.value })} placeholder="Last Name" className="border border-fn-gborder bg-fn-black px-3 py-2 text-sm outline-none"/></div><button onClick={saveProfile} className="fn-btn mt-3 inline-flex items-center gap-2"><Save size={14}/> Save Profile</button><p className="mt-2 text-[10px] text-fn-muted">Existing users can leave name fields empty until they choose to update them.</p></section>
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label mb-3 flex items-center gap-2"><SearchCheck size={12}/> Verify Bet</p><div className="flex gap-2"><input value={verifyCode} onChange={(e)=>setVerifyCode(e.target.value)} placeholder="FN26756 or verification ID" className="min-w-0 flex-1 border border-fn-gborder bg-fn-black px-3 py-2 text-xs uppercase outline-none"/><button onClick={verifyBet} className="fn-btn px-3">Verify</button></div>{verifyResult && <div className="mt-3 rounded-sm border border-fn-green/30 bg-fn-black/60 p-3 text-xs"><p className="font-black uppercase text-fn-green">Genuine FragNaija Wager Zone Slip · {verifyResult.slip_code || verifyResult.verification_id}</p><p className="mt-1 text-fn-muted">Status: {verifyResult.status} · Stake: ₦{Number(verifyResult.stake||0).toLocaleString()} · Redeemable now: {verifyResult.redeemable ? 'Yes' : 'No'}</p><div className="mt-2 space-y-1">{verifyResult.selections?.map((item: VerifiedSelection)=><p key={`${item.wager_id}-${item.selection}`} className="text-fn-text">{item.market?.match_name || item.market?.question}: <b>{item.selection}</b> @ live odds {Number(item.live_odds||0).toFixed(2)} · {item.available ? 'Available' : 'Closed/unavailable'}</p>)}</div></div>}</section>
    <section className="border border-fn-gborder bg-fn-card p-5"><button type="button" onClick={logout} className="fn-btn-outline inline-flex items-center gap-2"><LogOut size={14}/> Log Out</button></section>
    <section className="border border-fn-gborder bg-fn-card p-5"><p className="fn-label mb-3 flex items-center gap-2"><Gift size={12}/> Offers</p><div className="rounded-sm border border-fn-gborder bg-fn-black/60 p-3"><p className="text-xs text-fn-muted">Referral code</p><p className="mt-1 font-display text-xl font-black text-fn-green">{offers.referral_code || profile.referral_code || '—'}</p><p className="mt-1 break-all text-[10px] text-fn-muted">{referralUrl}</p></div><div className="mt-3 flex gap-2"><input value={promo} onChange={(e)=>setPromo(e.target.value)} placeholder="Enter promo code" className="min-w-0 flex-1 border border-fn-gborder bg-fn-black px-3 py-2 text-xs uppercase outline-none"/><button onClick={redeem} className="fn-btn px-3">Redeem</button></div><div className="mt-4 space-y-2">{(offers.referrals || []).map((ref)=><div key={ref.id} className="flex items-center justify-between border border-fn-gborder bg-fn-black/50 px-3 py-2 text-xs"><span>{ref.referred_display}</span><span className={ref.status === 'Qualified' ? 'text-fn-green' : 'text-fn-yellow'}>{ref.status} · ₦{Number(ref.bonus_amount_ngn||0).toLocaleString()}</span></div>)}</div></section>
  </div></main>;
}
